name: test

on:
  push:
    tag-ignore:
      - '**'

jobs:
  go:
    name: Go ${{matrix.go}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.21.x
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go}}
      - run: go vet ./...
      - run: go run honnef.co/go/tools/cmd/staticcheck@2023.1.6 ./...
      - run: go test -v ./...
      - run: go run ./cmd/snappr --help
